<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Smbc.Risk.Core.Application</AssemblyName>
    <RootNamespace>Smbc.Risk.Core.Application</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="NodaTime" Version="3.3.3" />
  </ItemGroup>

</Project>
